application: lanternxmpp
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

handlers:
#- url: /_ah/xmpp/message/chat/
- url: /.*
  script: xmpp.py

inbound_services:
- xmpp_message
- warmup
